import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

import ThemeProviderWrapper from '@/components/Theme/ThemeProviderWrapper'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer'
import { Toaster } from 'sonner'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'UpTodo',
	description: 'Generated by create next app',
	creator: 'ustymenko.denys@gmail.com',
}

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode
}>) => {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-dvh flex flex-col`}>
				<ThemeProviderWrapper>
					<Header />
					<main className='container flex flex-col items-center justify-center p-2 mx-auto border-dashed grow sm:border-x lg:p-4'>
						{children}
					</main>
					<Footer />
					<Toaster
						position='top-center'
						richColors
					/>
				</ThemeProviderWrapper>
			</body>
		</html>
	)
}

export default RootLayout
