import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Toaster } from 'sonner'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer'
import DetailsDialog from '@/components/Tasks/DetailsDialog/DetailsDialog'
import './globals.css'
import ProvidersTree from '@/components/providers/ProvidersTree'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
	preload: false,
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
	preload: false,
})

export const metadata: Metadata = {
	title: 'UpTodo',
	description: 'Generated by create next app',
	creator: 'ustymenko.denys@gmail.com',
}

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode
}>) => (
	<html lang='en'>
		<body
			className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-dvh flex flex-col`}>
			<ProvidersTree>
				<Header />
				<main className='container flex flex-col items-center justify-center p-2 mx-auto border-dashed grow sm:border-x lg:p-4'>
					{children}
				</main>
				<Footer />
				<DetailsDialog />
				<Toaster
					position='top-center'
					richColors
				/>
			</ProvidersTree>
		</body>
	</html>
)

export default RootLayout
